name: "Linux x86_64"

on: 
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 25
    steps:
      - name: "Code Checkout"
        uses: actions/checkout@v3

      - name: "Java Setup"
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: "Install Missing Packages"
        run: sudo apt-get update -y && sudo apt-get install -y ninja-build libgtk-3-dev

      - name: "Flutter Action"
        uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: '3.16.9'
          channel: 'stable'

      - name: "Flutter: Doctor"
        run: flutter doctor

      - name: "Flutter: Get Packages"
        run: flutter pub get

      - name: "Linux: Build for Linux"
        run: flutter build linux

      - name: "Linux: Tar Linux package"
        run: tar -C build/linux/x64/release/bundle -czf dateapp-linux-x64.tar.gz .

      - name: Release to GitHub
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dateapp-linux-x64.tar.gz"
          tag: ${{ steps.version.outputs.content }}
          commit: ${{ github.sha }}
          allowUpdates: true 
