name: "MacOS - Build"

on: 
  push:
    tags: ['v*']

jobs:
 build:
   runs-on: macos-latest
   permissions:
     contents: write
   steps:
    - name: "Code Checkout"
      uses: actions/checkout@v3
    
    - name: "Flutter Action"
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64

    - name: "Flutter: Enable MacOS Desktop"
      run: flutter config --enable-macos-desktop

    - name: "Flutter: Build MacOS"
      run: flutter build macos

    - name: Release to GitHub
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/macos/Build/Products/Release/dateapp.app"
        tag: ${{ steps.version.outputs.content }}
        commit: ${{ github.sha }}
        allowUpdates: true 

