name: "Windows - Build"

on: 
  push:
    tags: ['v*']

jobs:
 build:
   runs-on: windows-latest
   permissions:
      contents: write
   steps:
    - name: "Code Checkout"
      uses: actions/checkout@v3
    
    - name: "Flutter Action"
      uses: subosito/flutter-action@v2
      with:
        channel: 'beta'

    - name: Install required dart tools
      run: |
        dart pub global activate melos
        dart pub global activate vector_graphics_compiler

    - name: "Flutter: Enable Windows Desktop"  
      run: flutter config --enable-windows-desktop
      
    - name: Bootstrap
      run: melos bootstrap

    - name: Build and create the .msix installer
      run: dart run msix:create

    - name: Release to GitHub
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build\\windows\\x64\\runner\\Release\\dateapp-windows.msix"
        tag: ${{ steps.version.outputs.content }}
        commit: ${{ github.sha }}
        allowUpdates: true 
