name: "Windows - Build"

on: 
  push:
    tags: ['v*']

jobs:
 build:
   runs-on: windows-latest
   permissions:
      contents: write
      timeout-minutes: 25
   steps:
    - name: "Code Checkout"
      uses: actions/checkout@v3
    
    - name: "Flutter Action"
      uses: subosito/flutter-action@v2
      with:
        channel: 'beta'

    - name: "Flutter: Enable Windows Desktop"  
      run: flutter config --enable-windows-desktop

    - name: "Flutter: Build for Windows"
      run: flutter build windows

    - name: Release to GitHub
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build\\windows\\x64\\runner\\Release\\dateapp.exe"
        tag: ${{ steps.version.outputs.content }}
        commit: ${{ github.sha }}
        allowUpdates: true 
